### ISSUE TITLE
Logger cannot be resolved to a type and Red5LoggerFactory cannot be resolved

### ISSUE THREAD

**Issue by pol2095** [Red5/red5-examples#2]
Hello,

When I try to add oflaDemo classes on Eclipse, I have this error message : 
- Logger cannot be resolved to a type
- Red5LoggerFactory cannot be resolved

I add external jars : red5-server.jar and red5-service.jar

Thanks

**Comment by mondain** [comment]
You'll also need to add the red5-server-common.jar
