### ISSUE TITLE
Error building oflademo

### ISSUE THREAD

**Issue by jdc18** [Red5/red5-examples#3]
I am getting this error when I try to build oflademos
[ERROR] Failed to execute goal on project red5-example-oflaDemo: Could not resolve dependencies for project org.red5:red5-example-oflaDemo:war:2.0: Failure to find org:jaudiotagger:jar:2.0.4-SNAPSHOT in http://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> [Help 1]

**Comment by mondain** [comment]
We replaced jaudiotagger with tika, so I suppose this is just a pom modification needing to be done.

**Comment by mondain** [comment]
Ok, I updated the poms, it builds fine here now.
